# Generated by Django 6.0.1 on 2026-05-12 15:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categorie', models.AutoField(primary_key=True, serialize=False)),
                ('nom_categorie', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'db_table': 'categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id_membre', models.AutoField(primary_key=True, serialize=False)),
                ('numero_carte', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('date_naissance', models.DateField()),
                ('statut_compte', models.CharField(choices=[('Actif', 'Actif'), ('Suspendu', 'Suspendu'), ('Bloqué', 'Bloqué')], default='Actif', max_length=50)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('mot_de_passe_hash', models.CharField(max_length=255)),
                ('user_type', models.CharField(choices=[('member', 'Membre'), ('unified', 'Utilisateur Unifié')], default='member', max_length=50)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'db_table': 'membres',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TypeMembre',
            fields=[
                ('id_type_membre', models.AutoField(primary_key=True, serialize=False)),
                ('nom_type', models.CharField(max_length=100, unique=True)),
                ('duree_max_emprunt', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('nb_max_emprunt', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de Membre',
                'verbose_name_plural': 'Types de Membres',
                'db_table': 'types_membre',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id_auteur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auteur',
                'verbose_name_plural': 'Auteurs',
                'db_table': 'auteurs',
                'managed': True,
                'unique_together': {('nom', 'prenom')},
            },
        ),
        migrations.CreateModel(
            name='Bibliothecaire',
            fields=[
                ('id_bibliotecaire', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('mot_de_passe_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('agent', 'Agent Bibliothécaire')], default='agent', max_length=50)),
                ('user_type', models.CharField(choices=[('staff', 'Staff'), ('admin', 'Admin')], default='staff', max_length=50)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bibliothécaire',
                'verbose_name_plural': 'Bibliothécaires',
                'db_table': 'bibliothecaires',
                'managed': True,
                'indexes': [models.Index(fields=['login'], name='bibliotheca_login_495959_idx'), models.Index(fields=['role'], name='bibliotheca_role_09420b_idx'), models.Index(fields=['actif'], name='bibliotheca_actif_c2bee5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id_livre', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('editeur', models.CharField(blank=True, max_length=150, null=True)),
                ('langue', models.CharField(default='Français', max_length=50)),
                ('annee_publication', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('image_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('date_ajout_catalogue', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_categorie', models.ForeignKey(db_column='id_categorie', on_delete=django.db.models.deletion.PROTECT, to='core.categorie')),
            ],
            options={
                'verbose_name': 'Livre',
                'verbose_name_plural': 'Livres',
                'db_table': 'livres',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Exemplaire',
            fields=[
                ('id_exemplaire', models.AutoField(primary_key=True, serialize=False)),
                ('code_barre', models.CharField(max_length=100, unique=True)),
                ('etat', models.CharField(choices=[('Bon', 'Bon'), ('Abîmé', 'Abîmé'), ('Perdu', 'Perdu')], default='Bon', max_length=50)),
                ('statut_logique', models.CharField(choices=[('Disponible', 'Disponible'), ('Emprunté', 'Emprunté'), ('Réservé', 'Réservé'), ('Indisponible', 'Indisponible')], default='Disponible', max_length=50)),
                ('date_acquisition', models.DateField(auto_now_add=True)),
                ('localisation', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_livre', models.ForeignKey(db_column='id_livre', on_delete=django.db.models.deletion.CASCADE, related_name='exemplaires', to='core.livre')),
            ],
            options={
                'verbose_name': 'Exemplaire',
                'verbose_name_plural': 'Exemplaires',
                'db_table': 'exemplaires',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LivresAuteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_auteur', models.ForeignKey(db_column='id_auteur', on_delete=django.db.models.deletion.CASCADE, to='core.auteur')),
                ('id_livre', models.ForeignKey(db_column='id_livre', on_delete=django.db.models.deletion.CASCADE, to='core.livre')),
            ],
            options={
                'verbose_name': 'Livre-Auteur',
                'verbose_name_plural': 'Livres-Auteurs',
                'db_table': 'livres_auteurs',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='livre',
            name='auteurs',
            field=models.ManyToManyField(related_name='livres', through='core.LivresAuteur', to='core.auteur'),
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_livre', models.ForeignKey(db_column='id_livre', on_delete=django.db.models.deletion.CASCADE, to='core.livre')),
                ('id_membre', models.ForeignKey(db_column='id_membre', on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='core.membre')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'db_table': 'favoris',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id_emprunt', models.AutoField(primary_key=True, serialize=False)),
                ('date_emprunt', models.DateField(auto_now_add=True)),
                ('date_retour_prevue', models.DateField()),
                ('date_retour_effective', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('En cours', 'En cours'), ('Retourné', 'Retourné'), ('En retard', 'En retard')], default='En cours', max_length=50)),
                ('renouvellement_count', models.IntegerField(default=0)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_bibliotecaire', models.ForeignKey(blank=True, db_column='id_bibliotecaire', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bibliothecaire')),
                ('id_exemplaire', models.ForeignKey(db_column='id_exemplaire', on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='core.exemplaire')),
                ('id_membre', models.ForeignKey(db_column='id_membre', on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='core.membre')),
            ],
            options={
                'verbose_name': 'Emprunt',
                'verbose_name_plural': 'Emprunts',
                'db_table': 'emprunts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id_avis', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_avis', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_livre', models.ForeignKey(db_column='id_livre', on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='core.livre')),
                ('id_membre', models.ForeignKey(db_column='id_membre', on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='core.membre')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'db_table': 'avis',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id_message', models.AutoField(primary_key=True, serialize=False)),
                ('contenu', models.TextField()),
                ('reponse', models.TextField(blank=True, null=True)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Répondu', 'Répondu')], default='En attente', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_bibliotecaire', models.ForeignKey(blank=True, db_column='id_bibliotecaire', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_recus', to='core.bibliothecaire')),
                ('id_membre', models.ForeignKey(db_column='id_membre', on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to='core.membre')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notification', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('date_notif', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_membre', models.ForeignKey(db_column='id_membre', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.membre')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id_reservation', models.AutoField(primary_key=True, serialize=False)),
                ('date_reservation', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Disponible', 'Disponible'), ('Complétée', 'Complétée'), ('Annulée', 'Annulée')], default='En attente', max_length=50)),
                ('priorite', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_bibliotecaire', models.ForeignKey(blank=True, db_column='id_bibliotecaire', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bibliothecaire')),
                ('id_livre', models.ForeignKey(db_column='id_livre', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.livre')),
                ('id_membre', models.ForeignKey(db_column='id_membre', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.membre')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'db_table': 'reservations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id_sanction', models.AutoField(primary_key=True, serialize=False)),
                ('type_sanction', models.CharField(choices=[('Retard', 'Retard'), ('Détérioration', 'Détérioration'), ('Perte', 'Perte'), ('Autre', 'Autre')], max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_sanction', models.DateField(auto_now_add=True)),
                ('date_fin_suspension', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('Active', 'Active'), ('Payée', 'Payée'), ('Annulée', 'Annulée')], default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_bibliotecaire', models.ForeignKey(blank=True, db_column='id_bibliotecaire', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bibliothecaire')),
                ('id_emprunt', models.ForeignKey(blank=True, db_column='id_emprunt', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.emprunt')),
                ('id_membre', models.ForeignKey(db_column='id_membre', on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='core.membre')),
            ],
            options={
                'verbose_name': 'Sanction',
                'verbose_name_plural': 'Sanctions',
                'db_table': 'sanctions',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='membre',
            name='id_type_membre',
            field=models.ForeignKey(db_column='id_type_membre', on_delete=django.db.models.deletion.PROTECT, to='core.typemembre'),
        ),
        migrations.AddIndex(
            model_name='exemplaire',
            index=models.Index(fields=['code_barre'], name='exemplaires_code_ba_8d6f95_idx'),
        ),
        migrations.AddIndex(
            model_name='exemplaire',
            index=models.Index(fields=['statut_logique'], name='exemplaires_statut__83eb6f_idx'),
        ),
        migrations.AddIndex(
            model_name='exemplaire',
            index=models.Index(fields=['id_livre'], name='exemplaires_id_livr_b4c420_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='livresauteur',
            unique_together={('id_livre', 'id_auteur')},
        ),
        migrations.AddIndex(
            model_name='livre',
            index=models.Index(fields=['titre'], name='livres_titre_7cbe8e_idx'),
        ),
        migrations.AddIndex(
            model_name='livre',
            index=models.Index(fields=['isbn'], name='livres_isbn_81e167_idx'),
        ),
        migrations.AddIndex(
            model_name='livre',
            index=models.Index(fields=['id_categorie'], name='livres_id_cate_fd83e6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favori',
            unique_together={('id_membre', 'id_livre')},
        ),
        migrations.AddIndex(
            model_name='emprunt',
            index=models.Index(fields=['id_membre', 'statut'], name='emprunts_id_memb_45c77e_idx'),
        ),
        migrations.AddIndex(
            model_name='emprunt',
            index=models.Index(fields=['statut'], name='emprunts_statut_f2d744_idx'),
        ),
        migrations.AddIndex(
            model_name='emprunt',
            index=models.Index(fields=['date_retour_prevue'], name='emprunts_date_re_cf297d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='avis',
            unique_together={('id_livre', 'id_membre')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['id_membre', 'lu'], name='notificatio_id_memb_d0aaae_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-date_notif'], name='notificatio_date_no_a138ec_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['id_livre', 'statut'], name='reservation_id_livr_0c79a9_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['statut'], name='reservation_statut_d20d98_idx'),
        ),
        migrations.AddIndex(
            model_name='membre',
            index=models.Index(fields=['email'], name='membres_email_8f764c_idx'),
        ),
        migrations.AddIndex(
            model_name='membre',
            index=models.Index(fields=['login'], name='membres_login_087400_idx'),
        ),
        migrations.AddIndex(
            model_name='membre',
            index=models.Index(fields=['numero_carte'], name='membres_numero__0eeaf6_idx'),
        ),
        migrations.AddIndex(
            model_name='membre',
            index=models.Index(fields=['statut_compte'], name='membres_statut__453603_idx'),
        ),
    ]
