# Generated by Django 6.0.1 on 2026-05-13 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auteur',
            options={'managed': False, 'verbose_name': 'Auteur', 'verbose_name_plural': 'Auteurs'},
        ),
        migrations.AlterModelOptions(
            name='avis',
            options={'managed': False, 'verbose_name': 'Avis', 'verbose_name_plural': 'Avis'},
        ),
        migrations.AlterModelOptions(
            name='bibliothecaire',
            options={'managed': False, 'verbose_name': 'Bibliothécaire', 'verbose_name_plural': 'Bibliothécaires'},
        ),
        migrations.AlterModelOptions(
            name='categorie',
            options={'managed': False, 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='emprunt',
            options={'managed': False, 'verbose_name': 'Emprunt', 'verbose_name_plural': 'Emprunts'},
        ),
        migrations.AlterModelOptions(
            name='exemplaire',
            options={'managed': False, 'verbose_name': 'Exemplaire', 'verbose_name_plural': 'Exemplaires'},
        ),
        migrations.AlterModelOptions(
            name='favori',
            options={'managed': False, 'verbose_name': 'Favori', 'verbose_name_plural': 'Favoris'},
        ),
        migrations.AlterModelOptions(
            name='livre',
            options={'managed': False, 'verbose_name': 'Livre', 'verbose_name_plural': 'Livres'},
        ),
        migrations.AlterModelOptions(
            name='livresauteur',
            options={'managed': False, 'verbose_name': 'Livre-Auteur', 'verbose_name_plural': 'Livres-Auteurs'},
        ),
        migrations.AlterModelOptions(
            name='membre',
            options={'managed': False, 'verbose_name': 'Membre', 'verbose_name_plural': 'Membres'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'managed': False, 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'managed': False, 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'managed': False, 'verbose_name': 'Réservation', 'verbose_name_plural': 'Réservations'},
        ),
        migrations.AlterModelOptions(
            name='sanction',
            options={'managed': False, 'verbose_name': 'Sanction', 'verbose_name_plural': 'Sanctions'},
        ),
        migrations.AlterModelOptions(
            name='typemembre',
            options={'managed': False, 'verbose_name': 'Type de Membre', 'verbose_name_plural': 'Types de Membres'},
        ),
    ]
